package painter

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"
)

const githubAPI = "https://api.github.com"

func ResolveAccount(ctx context.Context, token string) (AccountInfo, error) {
	token = strings.TrimSpace(token)
	if token == "" {
		return AccountInfo{}, fmt.Errorf("GitHub token is required")
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, githubAPI+"/user", nil)
	if err != nil {
		return AccountInfo{}, err
	}
	applyGitHubHeaders(req, token)

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return AccountInfo{}, err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		body, _ := io.ReadAll(io.LimitReader(resp.Body, 4096))
		return AccountInfo{}, fmt.Errorf("GitHub account lookup failed: %s: %s", resp.Status, strings.TrimSpace(string(body)))
	}

	var info AccountInfo
	if err := json.NewDecoder(resp.Body).Decode(&info); err != nil {
		return AccountInfo{}, err
	}
	if info.Login == "" {
		return AccountInfo{}, fmt.Errorf("GitHub account response did not include a login")
	}
	if info.Name == "" {
		info.Name = info.Login
	}
	info.NoreplyMail = fmt.Sprintf("%d+%s@users.noreply.github.com", info.ID, info.Login)
	return info, nil
}

func ensureRepository(ctx context.Context, token string, owner string, repo string, publicRepo bool) (bool, error) {
	endpoint := fmt.Sprintf("%s/repos/%s/%s", githubAPI, owner, repo)
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, endpoint, nil)
	if err != nil {
		return false, err
	}
	applyGitHubHeaders(req, token)

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return false, err
	}
	defer resp.Body.Close()

	if resp.StatusCode == http.StatusOK {
		return false, nil
	}
	if resp.StatusCode != http.StatusNotFound {
		body, _ := io.ReadAll(io.LimitReader(resp.Body, 4096))
		return false, fmt.Errorf("GitHub repository check failed: %s: %s", resp.Status, strings.TrimSpace(string(body)))
	}

	payload := map[string]interface{}{
		"name":        repo,
		"private":     !publicRepo,
		"auto_init":   false,
		"description": "Contribution graph artwork generated by WallPainter.",
	}
	data, err := json.Marshal(payload)
	if err != nil {
		return false, err
	}

	createReq, err := http.NewRequestWithContext(ctx, http.MethodPost, githubAPI+"/user/repos", bytes.NewReader(data))
	if err != nil {
		return false, err
	}
	applyGitHubHeaders(createReq, token)
	createReq.Header.Set("Content-Type", "application/json")

	createResp, err := http.DefaultClient.Do(createReq)
	if err != nil {
		return false, err
	}
	defer createResp.Body.Close()

	if createResp.StatusCode != http.StatusCreated {
		body, _ := io.ReadAll(io.LimitReader(createResp.Body, 4096))
		return false, fmt.Errorf("GitHub repository creation failed: %s: %s", createResp.Status, strings.TrimSpace(string(body)))
	}

	time.Sleep(1200 * time.Millisecond)
	return true, nil
}

func applyGitHubHeaders(req *http.Request, token string) {
	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Accept", "application/vnd.github+json")
	req.Header.Set("X-GitHub-Api-Version", "2022-11-28")
	req.Header.Set("User-Agent", "WallPainter")
}
