// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {painter} from '../models';

export function LoadSettings():Promise<config.Settings>;

export function ResolveAccount(arg1:string):Promise<painter.AccountInfo>;

export function RunPainting(arg1:painter.RunRequest):Promise<painter.RunResult>;

export function SaveSettings(arg1:config.Settings):Promise<void>;
