// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function ResolveAccount(arg1) {
  return window['go']['main']['App']['ResolveAccount'](arg1);
}

export function RunPainting(arg1) {
  return window['go']['main']['App']['RunPainting'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}
